- name: Golang
  logo: go
  url: https://golang.org
  color: '#7FD6EA'
  projects:
    - url: https://github.com/JeremyMorgan/PersonWeb
    - url: https://github.com/JeremyMorgan/GoSqliteDemo
    - url: https://github.com/JeremyMorgan/HotCarAPI
    - url: https://github.com/JeremyMorgan/HotCar
    - url: https://github.com/JeremyMorgan/GoZipCodeDigitalOcean
    - url: https://github.com/JeremyMorgan/ZipCodeLookupGo
    - url: https://github.com/JeremyMorgan/Compare-Strings-Go
    - url: https://github.com/JeremyMorgan/ReadTextFileGo
    - url: https://github.com/JeremyMorgan/GoTempSensor
    - url: https://github.com/JeremyMorgan/FindTheBadGuys
    - url: https://github.com/JeremyMorgan/turkeytime-golang
    - url: https://github.com/JeremyMorgan/FindTheBadGuys

- name: .NET
  logo: dotnet
  url: https://docs.microsoft.com/en-us/dotnet/csharp/
  color: '#512BD4'
  projects:
    - url: https://github.com/JeremyMorgan/TruckGameDemo
    - url: https://github.com/JeremyMorgan/ZipToCityAzureFunction
    - url: https://github.com/JeremyMorgan/TurkeyTimeAPI
    - url: https://github.com/JeremyMorgan/Hands-on-dotnet-core
    - url: https://github.com/JeremyMorgan/fake-dotnetcore-api
    - url: https://github.com/JeremyMorgan/cmd-webpage-speed-tester
    - url: https://github.com/JeremyMorgan/Dapper-Demo-ConsoleApp
    - url: https://github.com/JeremyMorgan/Raspberry_Pi_Weather_Station_API
    - url: https://github.com/JeremyMorgan/Raspberry_Pi_Temperature_API
    - url: https://github.com/JeremyMorgan/ipcountrycode

- name: Python
  logo: python
  url: https://www.python.org
  color: '#3C78A9'
  projects:
    - url: https://github.com/JeremyMorgan/Raspberry_Pi_Weather_Station
    - url: https://github.com/JeremyMorgan/CPUMeminfo
    - url: https://github.com/JeremyMorgan/Hot-Car-Test
    - url: https://github.com/JeremyMorgan/Hands_on_Internet_of_Things
    - url: https://github.com/JeremyMorgan/Raspberry_Pi_Weather_Station_PY_API
    - url: https://github.com/JeremyMorgan/Raspberry-Pi-LED-Demo

- name: JavaScript
  logo: javascript  
  url: https://www.javascript.com
  color: '#F7DF1E'
  projects:
    - url: https://github.com/JeremyMorgan/Angular-Kickstart
    - url: https://github.com/JeremyMorgan/Rowena-Fire-Realtime
    - url: https://github.com/JeremyMorgan/bryant-fire-realtime
    - url: https://github.com/JeremyMorgan/two-bulls-realtime
    - url: https://github.com/JeremyMorgan/seotools
    - url: https://github.com/JeremyMorgan/Raspberry_Pi_Weather_Station_WebUI